Stop VC error C2308: concatenating mismatched wide strings due to splitting large strings into more manageable chunks. When concatenating strings, if any of the sub-strings are wide then gcc compiler promotes all of the sub-strings to wide ones but MS VC compiler doesn't (hence no errors using gcc on Linux builds).